apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: balunywaonemsaks 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: balunywaonemsaks 
    spec:
      containers:
        - name: balunywaonemsaks 
          image: onemsaks.azurecr.io/balunywaonemsaks
          ports:
          - containerPort: 80